function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "topic5"};
	this.sidHashMap["topic5"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "topic5:1"};
	this.sidHashMap["topic5:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "topic5:27"};
	this.sidHashMap["topic5:27"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "topic5:1"};
	this.sidHashMap["topic5:1"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "topic5:3"};
	this.sidHashMap["topic5:3"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Function-Call Subsystem"] = {sid: "topic5:27"};
	this.sidHashMap["topic5:27"] = {rtwname: "<Root>/Function-Call Subsystem"};
	this.rtwnameHashMap["<Root>/Lamp"] = {sid: "topic5:12"};
	this.sidHashMap["topic5:12"] = {rtwname: "<Root>/Lamp"};
	this.rtwnameHashMap["<Root>/Toggle Switch"] = {sid: "topic5:11"};
	this.sidHashMap["topic5:11"] = {rtwname: "<Root>/Toggle Switch"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "topic5:4"};
	this.sidHashMap["topic5:4"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "topic5:1:1"};
	this.sidHashMap["topic5:1:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:2"] = {sid: "topic5:1:2"};
	this.sidHashMap["topic5:1:2"] = {rtwname: "<S1>:2"};
	this.rtwnameHashMap["<S1>:4"] = {sid: "topic5:1:4"};
	this.sidHashMap["topic5:1:4"] = {rtwname: "<S1>:4"};
	this.rtwnameHashMap["<S1>:5"] = {sid: "topic5:1:5"};
	this.sidHashMap["topic5:1:5"] = {rtwname: "<S1>:5"};
	this.rtwnameHashMap["<S2>/In1"] = {sid: "topic5:28"};
	this.sidHashMap["topic5:28"] = {rtwname: "<S2>/In1"};
	this.rtwnameHashMap["<S2>/function"] = {sid: "topic5:29"};
	this.sidHashMap["topic5:29"] = {rtwname: "<S2>/function"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "topic5:30"};
	this.sidHashMap["topic5:30"] = {rtwname: "<S2>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
