function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "TrafficLight_StateFlow"};
	this.sidHashMap["TrafficLight_StateFlow"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "TrafficLight_StateFlow:1"};
	this.sidHashMap["TrafficLight_StateFlow:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "TrafficLight_StateFlow:1"};
	this.sidHashMap["TrafficLight_StateFlow:1"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Lamp"] = {sid: "TrafficLight_StateFlow:2"};
	this.sidHashMap["TrafficLight_StateFlow:2"] = {rtwname: "<Root>/Lamp"};
	this.rtwnameHashMap["<Root>/Lamp1"] = {sid: "TrafficLight_StateFlow:3"};
	this.sidHashMap["TrafficLight_StateFlow:3"] = {rtwname: "<Root>/Lamp1"};
	this.rtwnameHashMap["<Root>/Lamp2"] = {sid: "TrafficLight_StateFlow:4"};
	this.sidHashMap["TrafficLight_StateFlow:4"] = {rtwname: "<Root>/Lamp2"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "TrafficLight_StateFlow:6"};
	this.sidHashMap["TrafficLight_StateFlow:6"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<Root>/Out2"] = {sid: "TrafficLight_StateFlow:7"};
	this.sidHashMap["TrafficLight_StateFlow:7"] = {rtwname: "<Root>/Out2"};
	this.rtwnameHashMap["<Root>/Out3"] = {sid: "TrafficLight_StateFlow:8"};
	this.sidHashMap["TrafficLight_StateFlow:8"] = {rtwname: "<Root>/Out3"};
	this.rtwnameHashMap["<S1>:5"] = {sid: "TrafficLight_StateFlow:1:5"};
	this.sidHashMap["TrafficLight_StateFlow:1:5"] = {rtwname: "<S1>:5"};
	this.rtwnameHashMap["<S1>:4"] = {sid: "TrafficLight_StateFlow:1:4"};
	this.sidHashMap["TrafficLight_StateFlow:1:4"] = {rtwname: "<S1>:4"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "TrafficLight_StateFlow:1:1"};
	this.sidHashMap["TrafficLight_StateFlow:1:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:2"] = {sid: "TrafficLight_StateFlow:1:2"};
	this.sidHashMap["TrafficLight_StateFlow:1:2"] = {rtwname: "<S1>:2"};
	this.rtwnameHashMap["<S1>:8"] = {sid: "TrafficLight_StateFlow:1:8"};
	this.sidHashMap["TrafficLight_StateFlow:1:8"] = {rtwname: "<S1>:8"};
	this.rtwnameHashMap["<S1>:10"] = {sid: "TrafficLight_StateFlow:1:10"};
	this.sidHashMap["TrafficLight_StateFlow:1:10"] = {rtwname: "<S1>:10"};
	this.rtwnameHashMap["<S1>:9"] = {sid: "TrafficLight_StateFlow:1:9"};
	this.sidHashMap["TrafficLight_StateFlow:1:9"] = {rtwname: "<S1>:9"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
